version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: src/OrderManagement.Api/Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=ordermanagement;Username=postgres;Password=postgres
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=ordermanagement
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 